networks:
  mysql-network:
    driver: bridge

services:

  mysql:
    container_name: mysql-sandbox
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql-sandbox-database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init-database:/docker-entrypoint-initdb.d/init.sql
      - mysql-sandbox-data:/var/lib/mysql
    ports:
      - 3333:3306
    expose:
      - 3306
    networks:
      - mysql-network

volumes:
  mysql-sandbox-data:



